[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version="0.5.0-rc.2",features=["json","secrets"]}
rocket_sync_db_pools = {version="0.1.0-rc.2",features=["diesel_postgres_pool"]}
diesel = {version="1.4.8",features = ["postgres"]}
argon2 = { version = "0.4.1", features = ["parallel"] }
markdown-parser = "0.1.2"#TODO: DROP this in favor of render markdown client side
serde = { version = "1.0.144", features = ["derive"] }
chrono = "0.4.22"
serde_json = "1.0.85"
slug = "0.1.4"
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
hcaptcha = "2.1.1"
