package:
  name: Lunas-blog
  version: 0.1.1
  description: Luna's blog
  target-architecture:
    - amd64
    - aarch64
  copyright:
    - license: GPL-2.0-only
      paths:
        - "*"
  dependencies:
    runtime:
      - busybox
      - libpq
      - ca-certificates-bundle
      - openssl

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - musl-dev
      - ca-certificates-bundle
      - pkgconf 
      - openssl-dev
      - libpq-dev
      - busybox
      - cargo
pipeline:
  - name: Build Luna's blog
    runs: |
      EXEC_DIR="${{targets.destdir}}/usr/bin"
      BLOG_HOME="${{targets.destdir}}/"      
      TARGETDIR="$(mktemp -d)"
      mkdir -p "${BLOG_HOME}/media" "${EXEC_DIR}"
      cargo build --release --target-dir "${TARGETDIR}"
      cp "${TARGETDIR}/release/blog" "${EXEC_DIR}"
      cp wait-for-postgres.sh "${EXEC_DIR}"
      cp -rv static    "${{targets.destdir}}/static"
      cp -rv templates "${{targets.destdir}}/templates"